// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/statistics.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StatisticsService service

func NewStatisticsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StatisticsService service

type StatisticsService interface {
	Statistics(ctx context.Context, in *StatisticsRequest, opts ...client.CallOption) (*StatisticsReply, error)
}

type statisticsService struct {
	c    client.Client
	name string
}

func NewStatisticsService(name string, c client.Client) StatisticsService {
	return &statisticsService{
		c:    c,
		name: name,
	}
}

func (c *statisticsService) Statistics(ctx context.Context, in *StatisticsRequest, opts ...client.CallOption) (*StatisticsReply, error) {
	req := c.c.NewRequest(c.name, "StatisticsService.Statistics", in)
	out := new(StatisticsReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatisticsService service

type StatisticsServiceHandler interface {
	Statistics(context.Context, *StatisticsRequest, *StatisticsReply) error
}

func RegisterStatisticsServiceHandler(s server.Server, hdlr StatisticsServiceHandler, opts ...server.HandlerOption) error {
	type statisticsService interface {
		Statistics(ctx context.Context, in *StatisticsRequest, out *StatisticsReply) error
	}
	type StatisticsService struct {
		statisticsService
	}
	h := &statisticsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StatisticsService{h}, opts...))
}

type statisticsServiceHandler struct {
	StatisticsServiceHandler
}

func (h *statisticsServiceHandler) Statistics(ctx context.Context, in *StatisticsRequest, out *StatisticsReply) error {
	return h.StatisticsServiceHandler.Statistics(ctx, in, out)
}
